### ISSUE TITLE
Undefined variables in NSCBC

### ISSUE THREAD

**Issue by jrood-nrel** [AMReX-Combustion/PeleC#104]
It appears that in https://github.com/AMReX-Combustion/PeleC/blob/7c3b72da50323d1ca4c894028069c032bd7e98f2/Source/Src_3d/impose_NSCBC_3d.f90#L223 it's possible that `x_bc_params` will not be set. I have seen this cause NaNs in certain situations. Should the `if` statement at https://github.com/AMReX-Combustion/PeleC/blob/7c3b72da50323d1ca4c894028069c032bd7e98f2/Source/Src_3d/impose_NSCBC_3d.f90#L199 (and the other dimensions) account for this possibility?

**Comment by emotheau** [comment]
x_bc_params can be first initiated with dummy values, they will not be used in anyway if UserBC is not set.

**Comment by jrood-nrel** [comment]
@emotheau Do you have a pull request that will fix this undefined behavior?

**Comment by emotheau** [comment]
I have created one, does this fix everything?
