### ISSUE TITLE
Issues compiling using HYP_TYPE = MOL

### ISSUE THREAD

**Issue by ldowen** [AMReX-Combustion/PeleC#123]
I have a test case I am running. In 2d, I was able to get it to compile and run when I used HYP_TYPE = PPM. However, when I use HYP_TYPE = MOL, it fails to compile. I tried a series of configurations with HYP_TYPE = MOL with varying results:

1. For DIM = 2, USE_EB = FALSE, it fails to compile with the error that the amrex_ebcellflag_module can't be found from the slope_mod_2d_EB.f90 file.

2. For DIM = 2, USE_EB = TRUE, it fails to compile with the error that in Src_2d/trace_d2.f90, the uslope, pslope, and multid_slope symbols cannot be found in the slope_module.

3. For DIM = 3, USE_EB = FALSE, it again fails to find the amrex_ebcellflag_module.

4. For DIM = 3, USE_EB = TRUE, it compiles.

**Comment by jrood-nrel** [comment]
For 1 and 3, `HYP_TYPE=MOL` requires `USE_EB=TRUE`. I will update the makefiles to error out if this is not satisfied. For 2 I will try to solve this. It looks like the dependency of `slope_2d.f90` for `trace_2d.f90` is not being respected for some reason, so `slope_module` doesn't seem to get compiled in time for `trace_2d.f90` to find it. I'm not sure why it's fine for 3d when everything is mostly identical in 2d.

**Comment by jrood-nrel** [comment]
@ldowen, it seems you stumbled upon a few of the unsupported configurations in PeleC. Even 2 on your list is currently unsupported. I have a pull request to explicitly state that these configurations are unsupported. It will take some discussion with the team to decide if we want to support these configurations and what the correct way would be to do so. These unsupported configurations are remnants of when EB was introduced into the code.

**Comment by drummerdoc** [comment]
So, there is no 2D EB and no plans for it?

**Comment by jrood-nrel** [comment]
The only thing I know is that it doesn't work. `trace_2d.f90`, which doesn't work, looks entirely different than `trace_3d.f90`, which works.

**Comment by jrood-nrel** [comment]
I guess maybe we don't need the trace files? It looks like 2d with EB without the `trace_2d.f90` file compiles fine. I will try to narrow this stuff down next week.

**Comment by jrood-nrel** [comment]
Alright #125 should allow `DIM = 2, USE_EB = TRUE` to work again, and explicitly states that `HYP_TYPE=MOL` requires `USE_EB=TRUE`. So I think that will resolve this issue.
