### ISSUE TITLE
Compile error in regression Test PMF

### ISSUE THREAD

**Issue by hbrunie** [AMReX-Combustion/PeleC#129]
Hello,

I have been using git bisect to find a possible bug while compiling PeleC/Exec/RegTests/PMF.
Maybe I don't have the right environment:
I compile on Cori.
The modules loaded are:
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/5767146/67422006-7b072780-f586-11e9-8262-6b39df703c27.png">

I do make -j 32 on Haswell with the default GNUMakefile.

The  first "bad" commit is:

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/5767146/67421906-4b581f80-f586-11e9-8a54-274133134302.png">

Thanks,
 Hugo

**Comment by jrood-nrel** [comment]
@hbrunie Sorry, I just saw this issue. I will fix the notifications so I will see when issues are posted in the future.

I just tried this on Cori with the latest PeleC `development` branch and the PMF case compiles for me. Are you using the latest `development` branch of PeleC? It will also matter what commit of AMReX you are using. By default if you don't have `AMREX_HOME` set, it should use the AMReX in the submodules of PeleC, which I am using. I tried both `PrgEnv-intel`, which is the default on Cori, and `PrgEnv-gnu`, which is the default in the `GNUmakefile` for the PMF case. Both compiled for me. I would recommend using the Intel compiler as you will see better performance from PeleC.

**Comment by hbrunie** [comment]
I used two different kind of branches for this test. I used development for PeleC, but I used master for AMReX and PelePhysics. I also tried with all branched in master and it does not compile either. Nevertheless, I have been told I should use all repo with development branch, and indeed it works well. Maybe this should be mentioned somewhere in the doc that development branches should be used instead of master for all three repo.

Thanks for the insight about INTEL compiler performance.

Thanks,
 Hugo

**Comment by jrood-nrel** [comment]
Yeah, internally we almost exclusively use the `development` branches of PeleC, PelePhysics, and AMReX. We should probably just switch the default branches in this project to `development`. That is good insight. Glad it works for you now.
