### ISSUE TITLE
Homogeneous label name between PeleC and PeleLM

### ISSUE THREAD

**Issue by hbrunie** [AMReX-Combustion/PeleC#137]
The Compute_Sl tool from PeleLM could work on PMF from PeleC, if the temperature label name had no capital letter.

PeleLM: temp
PeleC: Temp

Maybe the label could be changed to be homogeneous with PeleLM?

**Comment by jrood-nrel** [comment]
Looking back at issues, I agree `Temp` should be changed because it is inconsistent with every other variable. However, if/when we change it, I think changing to `temperature` will be the most appropriate, which unfortunately won't solve your issue.

**Comment by hbrunie** [comment]
It was not really an issue, more a comment. I dealt with it adding a condition in the ComputeSl tool (condition which could be remove when both would have same name).

**Comment by jrood-nrel** [comment]
Ah ok. I will close this issue then and likely convert to `temperature` in the future.
