### ISSUE TITLE
Tutorials result "plt" could not view in VisIt or Paraview

### ISSUE THREAD

**Issue by wazedxwxx** [AMReX-Combustion/PeleC#139]
When I run the program in the tutorial,like EB_Channel.I could't visualize my data

1. Open "header" in VisIt .When I try to draw the "Pseudocolor" 
the error message is 
"**The compute engine running on localhost has exited abnormally.
Shortly thereafter, the following occured...**"
when I draw the mesh as follow as figure
![image](https://user-images.githubusercontent.com/59836980/72438597-1d2e5880-37e0-11ea-8572-8596cb44405c.png)

the message in concle is
**Segfault !!!
/usr/bin/addr2line: '/home/PeleC/Exec/Tutorials/EB_Channel/plt00010/visit': No such file**
See Backtrace.0 file for details

[Backtrace.0.txt](https://github.com/AMReX-Combustion/PeleC/files/4065196/Backtrace.0.txt)

2. Open "he/home/PeleC/Exec/Tutorials/EB_Channel/plt00010/Backtrace.0ader" in ParaView .Open the folder "plt00010" with AMRex/BoxLib Particles Reader
the error message is
![image](https://user-images.githubusercontent.com/59836980/72438826-a0e84500-37e0-11ea-8aeb-bc2eab2b1d7e.png)
3.my case is EB_Channel,in fact .I run the all of the Tutorials ,everycase all have the error
my input is:
[inputs.3d.txt](https://github.com/AMReX-Combustion/PeleC/files/4065209/inputs.3d.txt)
env is
++++++++++++++++++++++++++++++++++++++++++++
XDG_VTNR=1
CPLUS_INCLUDE_PATH=/usr/local/zlib/1.2.8/include:/usr/local/zlib/1.2.8/include:
MANPATH=/root/sfw/linux/openmpi/1.10.2/share/man:/root/sfw/linux/openmpi/1.10.2/share/man::/usr/local/texlive/2019/texmf-dist/doc/man:/root/sfw/linux/openmpi/1.10.2/share/man::/usr/local/texlive/2019/texmf-dist/doc/man:/root/sfw/linux/openmpi/1.10.2/share/man:/root/sfw/linux/openmpi/1.10.2/share/man::/usr/local/texlive/2019/texmf-dist/doc/man:/root/sfw/linux/openmpi/1.10.2/share/man:
SSH_AGENT_PID=3417
XDG_SESSION_ID=1
AMREX_HOME=/home/AMReX
DBUS_STARTER_ADDRESS=unix:abstract=/tmp/dbus-FnhZu47jgV,guid=5b8fd94f1eb29e04e53c73be5e1efb27
HOSTNAME=localhost.localdomain
IMSETTINGS_INTEGRATE_DESKTOP=yes
BLD_ROOT=/home/asc/vtf/gnu-opt-mpi
TERM=xterm-256color
VTE_VERSION=5202
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
HISTSIZE=1000
PETSC_ARCH=linux-opt
LIBRARY_PATH=/usr/local/zlib/1.2.8/lib:/usr/local/zlib/1.2.8/lib:
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/e0c66b5e_41e0_44ad_a44d_0beab8902b47
IMSETTINGS_MODULE=none
QT_GRAPHICSSYSTEM_CHECKED=1
USER=root
LD_LIBRARY_PATH=/root/Chombo-3.2/lib:/usr/local/hdf5/hdf5_1.8.16/lib:/usr/local/octave/5.1.10/bin/lib:/usr/lib/python2.7/:/usr/local/zlib/1.2.8/lib:/root/Chombo-3.2/lib:/usr/local/hdf5/hdf5_1.8.16/lib:/usr/local/octave/5.1.10/bin/lib:/usr/lib/python2.7/:/usr/local/zlib/1.2.8/lib:
GNOME_TERMINAL_SERVICE=:1.147
SSH_AUTH_SOCK=/run/user/0/keyring/ssh
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/3280,unix/unix:/tmp/.ICE-unix/3280
USERNAME=root
GNOME_SHELL_SESSION_MODE=classic
DESKTOP_SESSION=gnome-classic
MAIL=/var/spool/mail/root
PATH=/root/bin:/home/asc/vtf/gnu-opt-mpi/bin:/root/bin:/usr/local/vim/bin:/usr/local/octave/5.1.10/bin:/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/visit/bin:/root/sfw/linux/openmpi/1.10.2/bin:/root/bin:/root/bin:/usr/local/vim/bin:/usr/local/octave/5.1.10/bin:/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/visit/bin:/root/sfw/linux/openmpi/1.10.2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin:/usr/local/vim/bin:/usr/local/octave/5.1.10/bin:/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/visit/bin:/root/sfw/linux/openmpi/1.10.2/bin:/root/bin:/root/bin:/home/asc/vtf/gnu-opt-mpi/bin:/root/bin:/usr/local/vim/bin:/usr/local/octave/5.1.10/bin:/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/visit/bin:/root/sfw/linux/openmpi/1.10.2/bin:/root/bin:/root/bin:/usr/local/vim/bin:/usr/local/octave/5.1.10/bin:/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/visit/bin:/root/sfw/linux/openmpi/1.10.2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin:/usr/local/vim/bin:/usr/local/octave/5.1.10/bin:/usr/local/texlive/2019/bin/x86_64-linux:/usr/local/visit/bin:/root/sfw/linux/openmpi/1.10.2/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/root/bin
XIM=fcitx
QT_IM_MODULE=fcitx
C_INCLUDE_PATH=/usr/local/zlib/1.2.8/include:/usr/local/zlib/1.2.8/include:
XDG_SESSION_TYPE=x11
PWD=/home/PeleC/Exec/Tutorials/EB_Channel
XMODIFIERS=@im=fcitx
LANG=zh_CN.UTF-8
GDM_LANG=zh_CN.UTF-8
MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
LOADEDMODULES=
GDMSESSION=gnome-classic
PELEC_HOME=/home/PeleC
HISTCONTROL=ignoredups
DBUS_STARTER_BUS_TYPE=session
SHLVL=2
HOME=/root
XDG_SEAT=seat0
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
PYTHONPATH=/home/asc/vtf/gnu-opt-mpi/./amroc/modules
XDG_SESSION_DESKTOP=gnome-classic
LOGNAME=root
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-FnhZu47jgV,guid=5b8fd94f1eb29e04e53c73be5e1efb27
XDG_DATA_DIRS=/root/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/
MODULESHOME=/usr/share/Modules
LESSOPEN=||/usr/bin/lesspipe.sh %s
PELE_PHYSICS_HOME=/home/PelePhysics
INFOPATH=:/usr/local/texlive/2019/texmf-dist/doc/info:/usr/local/texlive/2019/texmf-dist/doc/info
WINDOWPATH=1
XDG_RUNTIME_DIR=/run/user/0
DISPLAY=:0
GTK_IM_MODULE=fcitx
XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME
PETSC_DIR=/root/sfw/petsc/3.10.5
XAUTHORITY=/run/gdm/auth-for-root-655Tx5/database
COLORTERM=truecolor
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd bash $*`
}
_=/usr/bin/env
OLDPWD=/home/PeleC/Exec/Tutorials

**Comment by marchdf** [comment]
Hi, did you try replacing `CartGrid-V2.0` with `HyperClawV1.1` in the `header`?

**Comment by wazedxwxx** [comment]
> Hi, did you try replacing `CartGrid-V2.0` with `HyperClawV1.1` in the `header`?

It's useful ! So appreciate!
