### ISSUE TITLE
Crashing (regression) with EB

### ISSUE THREAD

**Issue by asmunder** [AMReX-Combustion/PeleC#143]
I've been running some cases with PeleC with embedded boundaries, of an expanding channel with a flame (3D). Recently I pulled and compiled with the latest development branch of PeleC & PelePhysics & Amrex, probably had not done that since september-ish.

After this pull, all the EB cases I run (even tutorials like EB_Channel) crash after a few timesteps with error messages like shown in the quote below. If I deactivate EB (and MOL) the same cases run fine.

Is there a known regression I'm hitting? Maybe even a known fix? :)

Unfortunately I haven't been able to identify a consistent set of commits that I can return to for running my cases while this is being fixed. If anyone knows of such a set, I'd be very happy to hear about it.

> [Level 1 step 2] ADVANCE with dt = 1.387528863e-08
> ... Computing MOL source term at t^{n}
> ... Computing MOL source term at t^{n+1}
> 
>  >>> Error: PeleC_util.F90::compute_temp            3         112          13
>  >>> ... density out of bounds  -1.8103574798193642E-003
> 
> amrex::Error::205::Error:: compute_temp_nd.f90 !!!
> SIGABRT
>

**Comment by marchdf** [comment]
Hi @asmunder , thanks for bringing this up. I am looking into this and I am not able to reproduce. I am using the development branch of PeleC with the submodules of PelePhysics and AMReX set to the default:
```
PeleC: 1821d368af9040809e508e3b8586fcb770dcd45c
PelePhysics: d62fe39251ac46a08c37db6c27f6971b69224b47
AMReX: 93fb085d28349cab33892726dfa3107a85a7719e
```
I ran the EB_Channel case for 42 steps and didn't see an issue. All the nightly regression tests are passing as well. 

Maybe something else is going on? I will see if updating PelePhysics makes a difference.

**Comment by marchdf** [comment]
I tried EB_channel with latest PelePhysics and AMReX development :
```
PelePhysics: bc57ca7cbb709d75b47844f24fb9cef5df05ab43
AMReX: 90854ff447f414578ea982e0d745a8a3ffebcfcc
```
and it ran > 90 steps. 

Have you tried a `make realclean` to make sure no files are left from a strange step? And you can try the hashes I posted?

**Comment by asmunder** [comment]
Hi @marchdf , thanks for the quick follow-up.

Yes, I've done `make realclean`, and when running the EB_Channel to cross-check, it was a fresh copy from PeleC/Exec/Tutorials.

I went digging some more in my logs and identified the following set of commits that I had used at one point:
`
PeleC: d3917b5fa03467f24cfd
PelePhysics: ac196177a4708bfe5c94f40
AMRex: tag 19.11
`
With these, everything works. So at least I have one working set again.
I will try also the current submodules set of commits that you gave in your first reply.

**Comment by asmunder** [comment]
Update: it also works fine with the set of hashes that you posted:
```
PeleC: 1821d368af9040809e508e3b8586fcb770dcd45c
PelePhysics: d62fe39251ac46a08c37db6c27f6971b69224b47
AMReX: 93fb085d28349cab33892726dfa3107a85a7719e 
```
Guess I just got unlucky with whatever combination of hashes I got when I did my update. I guess we can close this issue. Thank you for the help :)

**Comment by marchdf** [comment]
Great!
