### ISSUE TITLE
Compilation issue gcc 9.3.0 CentOS 7

### ISSUE THREAD

**Issue by gmfricke** [AMReX-Combustion/PeleC#256]
Hello,

I am supporting several users who report they cannot compile PeleC under CentOS 7.9.2009 on our HPC systems. I am also unable to compile the code.  We have tried gcc 4.8.2, gcc 8.2, and gcc 9.3.0. One user at least reports they can compile with gcc 9.3.0 on their home machine. Under CentOS the errors depend on the version of gcc, but for gcc 9.3.0 we get:

module load gcc-9.3.0-gcc-9.2.0-f67yyal
export PELEC_HOME=${HOME}/users/laggad/PeleC
cd ${PELEC_HOME}/Exec/RegTests/PMF
make clean
make
<snip>
g++  -Werror=return-type -g -O3 -std=c++11  -pthread    -DBL_NO_FORT -DAMREX_GIT_VERSION=\"21.01-47-gc2beebd492f1\" -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DNDEBUG -DCRSEGRNDOMP -DPELEC_USE_REACTIONS -DPELEC_EOS_FUEGO -Itmp_build_dir/s/3d.gnu.EXE -I. -I../../../Submodules/PelePhysics/Eos/Fuego -I../../../Submodules/PelePhysics/Reactions -I../../../Submodules/PelePhysics/Transport/Simple -I../../../Submodules/AMReX/Src/Base -I../../../Submodules/AMReX/Src/Amr -I../../../Submodules/AMReX/Src/Boundary -I../../../Submodules/AMReX/Src/AmrCore -I. -I../../../Submodules/PelePhysics/Eos/Fuego -I../../../Submodules/PelePhysics/Support/Fuego/Evaluation -I../../../Submodules/PelePhysics/Support/Fuego/Mechanism/Models/LiDryer -I../../../Submodules/PelePhysics/Transport/Simple -I../../../Submodules/AMReX/Src/Base -I../../../Submodules/AMReX/Src/Amr -I../../../Submodules/AMReX/Src/Boundary -I../../../Submodules/AMReX/Src/AmrCore -I../../../Source -I../../../Source/Params/param_includes -I../../../Submodules/AMReX/Tools/C_scripts -c ../../../Source/PeleC.cpp -o tmp_build_dir/o/3d.gnu.EXE/PeleC.o
../../../Source/PeleC.cpp: In constructor ‘PeleC::PeleC(amrex::Amr&, int, const amrex::Geometry&, const amrex::BoxArray&, const amrex::DistributionMapping&, amrex::Real)’:
../../../Source/PeleC.cpp:417:32: error: ‘make_unique’ is not a member of ‘std’
     old_sources[src_list[n]] = std::make_unique<amrex::MultiFab>(
                                ^
../../../Source/PeleC.cpp:417:64: error: expected primary-expression before ‘>’ token
     old_sources[src_list[n]] = std::make_unique<amrex::MultiFab>(
                                                                ^
../../../Source/PeleC.cpp:419:32: error: ‘make_unique’ is not a member of ‘std’
     new_sources[src_list[n]] = std::make_unique<amrex::MultiFab>(
                                ^
../../../Source/PeleC.cpp:419:64: error: expected primary-expression before ‘>’ token
     new_sources[src_list[n]] = std::make_unique<amrex::MultiFab>(
                                                                ^
../../../Source/PeleC.cpp: In member function ‘const amrex::iMultiFab* PeleC::build_interior_boundary_mask(int)’:
../../../Source/PeleC.cpp:2157:21: error: ‘make_unique’ is not a member of ‘std’
   ib_mask.push_back(std::make_unique<amrex::iMultiFab>(
                     ^
../../../Source/PeleC.cpp:2157:54: error: expected primary-expression before ‘>’ token
   ib_mask.push_back(std::make_unique<amrex::iMultiFab>(
                                                      ^
make: *** [tmp_build_dir/o/3d.gnu.EXE/PeleC.o] Error 1

Any help would be appreciated.

All the best,

Matthew

**Comment by drummerdoc** [comment]
Hi Matthew.  Sorry for your difficulties.  Can you create a file in amrex/Tools/GNUMake called ``Make.local`` that contains just the single line: 
`CXXFLAGS += -std=c++17`
then ``make clean`` and try rebuilding to see if that fixes it?

**Comment by jrood-nrel** [comment]
`-std=c++14` is required for `make_unique`. We haven't tested if `c++17` will work. However, it shows `-std=c++11` in the compile line given. So to me that seems like the AMReX version is out of date since it should be adding `-std=c++14` automatically. I would recommend using the latest PeleC `development` branch and doing `git submodule init && git submodule update` to get the latest AMReX we are currently using. I would also recommend not setting a `PELEC_HOME`. It should not be necessary.

**Comment by gmfricke** [comment]
@drummerdoc Thank you, the compilation succeeded with your modification. I have asked our users to test functionality.

**Comment by drummerdoc** [comment]
@gmfricke Can you try @jrood-nrel 's suggestion as well and see if that works.  If not, we need to patch up AMReX for your system so it'd be good to know.  Thanks!

**Comment by gmfricke** [comment]
@drummerdoc @jrood-nrel Yes, the submodule update also allowed me to compile. Thanks again. The user I am supporting also reports they were able to compile and run the code. All the best, Matthew

**Comment by jrood-nrel** [comment]
Excellent. Thanks for reporting back. I am going to close this then. Please open more issues in the future if you encounter any problems.
