### ISSUE TITLE
Turbulence generator script "gen_hit_ic.py" missing from directory for HIT test case

### ISSUE THREAD

**Issue by ashwathsv** [AMReX-Combustion/PeleC#266]
Hi, I am trying to run the HIT test case in Exec/RegTests/HIT for different resolutions. When I try to setup the initial conditions, it looks like the script to generate initial conditions "gen_hit_ic.py" is missing in the directory. Where can I find this script? Thanks in advance!

**Comment by marchdf** [comment]
Hi, that script should be there... Let me see if somehow it got lost.
