### ISSUE TITLE
Compilation error - development branch

### ISSUE THREAD

**Issue by shashankNREL** [AMReX-Combustion/PeleC#288]
The current development branch of PeleC is giving the following compilation error. 

To reproduce the error - compile the PMF case with Sundials and CVODE turned on 

`(make -j8 TPLrealclean; make -j8 USE_SUNDIALS_PP=TRUE USE_CVODE_PP=TRUE TPL; make -j8 realclean; make -j8 USE_SUNDIALS_PP=TRUE USE_CVODE_PP=TRUE)`

`../../../Source/PeleC.cpp:32:10: fatal error: reactor.H: No such file or directory
 #include "reactor.H"
          ^~~~~~~~~~~
compilation terminated.`

**Comment by hsitaram** [comment]
set the Reactor_dir. use make -j USE_SUNDIALS_PP=TRUE Reactor_dir=cvode USE_CVODE_PP=TRUE

**Comment by shashankNREL** [comment]
Thanks @hsitaram

**Comment by jrood-nrel** [comment]
Thanks @hsitaram  . You should only need `Reactor_dir=cvode`. `USE_CVODE_PP` doesn't exist. Only `USE_ARKODE_PP` does. With `Reactor_dir != rk64`, `USE_SUNDIALS_PP` should get turned on automatically.
