### ISSUE TITLE
Compilation error --Exec/RegTests/PMF

### ISSUE THREAD

**Issue by wazedxwxx** [AMReX-Combustion/PeleC#308]
The current use of "USE_CUDA = TRUE" will cause the following problems

"nvcc  -ccbin=g++ -Xcompiler=' -Werror=return-type -g -O3  -pthread  -std=c++14' --std=c++14 -Wno-deprecated-gpu-targets -m64 -arch=compute_60 -code=sm_60 -maxrregcount=255 --expt-relaxed-constexpr --expt-extended-lambda -Xcudafe --diag_suppress=esa_on_defaulted_function_ignored --Werror cross-execution-space-call -lineinfo --ptxas-options=-O3 --ptxas-options=-v --use_fast_math  -x cu -dc   -DBL_NO_FORT -DAMREX_GIT_VERSION=\"\" -DAMREX_USE_GPU_RDC -DAMREX_USE_CUDA -DAMREX_USE_GPU -DBL_COALESCE_FABS -DBL_SPACEDIM=3 -DAMREX_SPACEDIM=3 -DBL_FORT_USE_UNDERSCORE -DAMREX_FORT_USE_UNDERSCORE -DBL_Linux -DAMREX_Linux -DNDEBUG -DAMREX_GPU_MAX_THREADS=256 -DCRSEGRNDOMP -DPELEC_USE_REACTIONS -DPELEC_EOS_FUEGO -Itmp_build_dir/s/3d.gnu.CUDA.EXE -I. -I../../../Submodules/PelePhysics/Source -I../../../Submodules/PelePhysics/Eos/Fuego -I../../../Submodules/PelePhysics/Reactions -I../../../Submodules/PelePhysics/Transport/Simple -I../../../Submodules/AMReX/Src/Base -I../../../Submodules/AMReX/Src/Amr -I../../../Submodules/AMReX/Src/Boundary -I../../../Submodules/AMReX/Src/AmrCore -I. -I../../../Submodules/PelePhysics/Source -I../../../Submodules/PelePhysics/Eos/Fuego -I../../../Submodules/PelePhysics/Reactions -I../../../Submodules/PelePhysics/Support/Fuego/Evaluation -I../../../Submodules/PelePhysics/Support/Fuego/Mechanism/Models/LiDryer -I../../../Submodules/PelePhysics/Transport/Simple -I../../../Submodules/AMReX/Src/Base -I../../../Submodules/AMReX/Src/Amr -I../../../Submodules/AMReX/Src/Boundary -I../../../Submodules/AMReX/Src/AmrCore -I../../../Source -I../../../Source/Params/param_includes -I../../../Submodules/AMReX/Tools/C_scripts -isystem /usr/local/cuda/include -c ../../../Submodules/PelePhysics/Support/Fuego/Mechanism/Models/LiDryer/mechanism.cpp -o tmp_build_dir/o/3d.gnu.CUDA.EXE/mechanism.o
../../../Submodules/PelePhysics/Support/Fuego/Mechanism/Models/LiDryer/mechanism.H(2304): warning: variable "k_r" was declared but never referenced
Segmentation fault (core dumped)
../../../Submodules/AMReX/Tools/GNUMake/Make.rules:198: recipe for target 'tmp_build_dir/o/3d.gnu.CUDA.EXE/mechanism.o' failed
make: *** [tmp_build_dir/o/3d.gnu.CUDA.EXE/mechanism.o] Error 139"

--->The current  cuda  version is 10.0, gcc version is 7.5.0.

--->The current GNUmakefile is set to

"# AMReX
DIM = 3
COMP = gnu
PRECISION = DOUBLE

PROFILE = FALSE
TINY_PROFILE = FALSE
COMM_PROFILE = FALSE
TRACE_PROFILE = FALSE
MEM_PROFILE = FALSE
USE_GPROF = FALSE

USE_MPI = FALSE
USE_OMP = FALSE
USE_CUDA = TRUE
USE_HIP = FALSE
USE_DPCPP = FALSE

DEBUG = FALSE
FSANITIZER = FALSE
THREAD_SANITIZER = FALSE

USE_REACT = TRUE
Reactor_dir := rk64
USE_EB = FALSE
USE_MASA = FALSE
Eos_dir := Fuego
Chemistry_Model := LiDryer
Transport_dir := Simple

Bpack := ./Make.package
Blocs := .
PELEC_HOME := ../../..
include $(PELEC_HOME)/Exec/Make.PeleC"

**Comment by jrood-nrel** [comment]
@wazedxwxx I can verify that CUDA 10.0 with GCC 7.5.0 exhibits a segmentation fault in CUDA's `nvcc` compiler when trying to compile our `mechanism.cpp` files, which are usually very large amounts of source code. Unfortunately this is a problem with Nvidia's compiler. We have verified that CUDA 10.1 with GCC 7.5.0 works for us, so it should work for you if you have that as an option. We also typically compile with GCC 8.4.0 and CUDA 10.2 or 11.2 which should work for you as well.

**Comment by marchdf** [comment]
Closing as it looks like the issue was addressed. Please reopen if not.
