### ISSUE TITLE
Running EB-C11 with higher levels of AMR throws error

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleC#309]
Hello everyone, 

I tried running the EB-C11 (Multispecies Sod Shock Tube) with ```amr.max_level = 2``` after introducing tagging based on temperature as: 
```
tagging.tempgrad = 1000
tagging.max_tempgrad_lev = 3
```
I get the following error: 

```
Doing initial redistribution... 
amrex::Abort::0::Grids must be properly nested for EB !!!
SIGABRT
See Backtrace.0 file for details
```
Anything I am missing here? 

Thanks a lot

**Comment by drummerdoc** [comment]
Can you try doubling the blocking factor and running again?

**Comment by RSuryaNarayan** [comment]
Thanks a lot, just works fine.
