### ISSUE TITLE
GPU used in EB RegTests

### ISSUE THREAD

**Issue by wazedxwxx** [AMReX-Combustion/PeleC#348]
I tried to use nvcc to compile several test examples using EB. But part of the compilation fails, and the other part of the compilation will diverge. Are there any tests that can run successfully on the GPU? If so, please tell me which one it is and I will be very grateful for your help :)

**Comment by jrood-nrel** [comment]
@wazedxwxx PeleC is tested nightly on Nivida GPUs with about 14 EB test cases. https://my.cdash.org/index.php?project=PeleC . If you would like to post your errors, we can try to assist you in troubleshooting them.

**Comment by wazedxwxx** [comment]
> @wazedxwxx PeleC is tested nightly on Nivida GPUs with about 14 EB test cases. https://my.cdash.org/index.php?project=PeleC . If you would like to post your errors, we can try to assist you in troubleshooting them.

When I use nvcc to run EB-C[_**5-8,14**_], it will suspend in “**Using quadratic stencil for the EB gradient**” .When using MPI and GPU, the error is "**Using quadratic stencil for the EB gradient terminate called after throwing an instance of 'thrust::system::system_error' what():  merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered**"
When I use nvcc to run EB-C[_**9-13**_], the result will diverge and produce the value of **Nan**.
The change I made is to make "**USE_CUDA=TRUE**" in GNUmakefile. But it does not seem to make the program run correctly on the GPU device.
My CUDA compiler version is: Cuda compilation tools, release 11.4, **V11.4.100**

By the way, I can successfully use the GPU to run the EB-BluffBody test. But one issue is that GPU computing is slower than MPI computing, even if MPI only uses 2 processors. My GPU is Quadro P2200.

**Comment by wazedxwxx** [comment]
> @wazedxwxx PeleC is tested nightly on Nivida GPUs with about 14 EB test cases. https://my.cdash.org/index.php?project=PeleC . If you would like to post your errors, we can try to assist you in troubleshooting them.

**Comment by wazedxwxx** [comment]
@jrood-nrel This should be a specific issue about CUDA installation and hardware. After changing the hardware, recompile, all test cases of EB have been compiled by nvcc successfully.Thank you for your help !
