### ISSUE TITLE
Failed to build PeleC due to sundials

### ISSUE THREAD

**Issue by Jokeren** [AMReX-Combustion/PeleC#366]
Hi, I checked out the latest PeleC and tried to build the PMF example. However, I encountered the following problem.

```
/home/kz21/Codes/PeleC/Submodules/sundials/include/sundials/sundials_types.h:53:10: fatal error: sundials/sundials_config.h: No such file or directory                
 #include <sundials/sundials_config.h>  
```

I wonder if sundials has to be build before any other dependent modules? FYI, an older commit `8f248555c1e7d809597049a18d024c4045c5d1c9` works for me.

**Comment by jrood-nrel** [comment]
Yes @Jokeren , sorry this probably isn't reflected anywhere in the documentation yet, but SUNDIALS is now a requirement for PeleC. In any `Exec` directory you can use the `TPL` target to build SUNDIALS. For example `make -j8 USE_MPI=FALSE COMP=llvm TPL`. Or if you use CMake, SUNDIALS will be built automatically during the regular make process.

Edit: Also, `make TPL` should happen automatically if SUNDIALS has not been found by the make system.

**Comment by jrood-nrel** [comment]
I should mention the reason we do this is so that we can now choose which ODE chemistry integrator we want to use at runtime, for example `pelec.chem_integrator=ReactorRK64`, or `pelec.chem_integrator=ReactorArkode`, or `pelec.chem_integrator=ReactorCvode`.

**Comment by Jokeren** [comment]
@jrood-nrel Thanks for your reply!

`make TPL` then `make` worked for the PMF example, but only using `make` didn't work.
