### ISSUE TITLE
EB RregTest occur oscillation behind the shock surface

### ISSUE THREAD

**Issue by wazedxwxx** [AMReX-Combustion/PeleC#368]
Hello everyone,
        I am trying to simulate shock interacting with a ramp using PeleC. I make changes on EB C-14. The difference is that I changed the angle of the ramp to 37 and the inflow Mach number to Ma = 4.5. But there will be oscillations after the shock.
![pc1](https://user-images.githubusercontent.com/59836980/139445627-20b8e8c2-581a-4313-96a4-28c0ce5bbefb.png)

The number of grids in the figure above is **2048 x 1536**. No mesh refinement is used in the calculation. I will submit the specific settings in the attachment.
[EB_RampShock.zip](https://github.com/AMReX-Combustion/PeleC/files/7442451/EB_RampShock.zip)

I tried to use a coarse mesh to dissipate the oscillation.But the effect is not very good. 
I also tried the artificial viscosity coefficient, but found no difference after changing **pelec.difmag**.
My question is whether my artificial viscosity factor is set correctly. And the cause of this non-physical oscillation and how to suppress it. Is it related to the EB method of the boundary?Extend my sincerest thanks in advance.

**Comment by hsitaram** [comment]
can you try pelec.use_laxf_flux =1. It will use the lax friedrichs flux which will add a bit more dissipation

**Comment by marchdf** [comment]
One thing to note is that since this is an EB problem, it uses the MOL method for the hydrodynamics. `pelec.difmag` is a control for the other way of computing the hydrodynamic term (Godunov, via PPM or PLM, this is unavailable for EB problem for now (we hope to change that in the future)).

**Comment by wazedxwxx** [comment]
> can you try pelec.use_laxf_flux =1. It will use the lax friedrichs flux which will add a bit more dissipation

Thank you very much! Using lax-friedrichs flow to get more dissipation. Oscillation behind the shock surface is suppressed.
This is a very useful option.

![Untitled](https://user-images.githubusercontent.com/59836980/139641320-91a9983e-eb10-4ad5-a2cd-d71188841d76.png)
![Untitled1](https://user-images.githubusercontent.com/59836980/139641333-4e1c6e57-27e3-47de-9b95-0f4e8e8627df.png)

**Comment by wazedxwxx** [comment]
> One thing to note is that since this is an EB problem, it uses the MOL method for the hydrodynamics. `pelec.difmag` is a control for the other way of computing the hydrodynamic term (Godunov, via PPM or PLM, this is unavailable for EB problem for now (we hope to change that in the future)).

Thank you very much for your reminder！As you pointed out, I found that changing pelec.difmag has no effect on the MOL method. 
In addition, as described in the PeleC document, the MOL method refers to a advance time step method. In the spatial discretization, the left and right fluxes of the surface are extrapolated through the characteristic line. The Riemann problem of the element surface is solved by using PVRS. 
I would like to ask you if there are any references for this kind of method ? I would like to find more comments on the accuracy of this method in these references.

**Comment by marchdf** [comment]
Glad the `lax_friedrichs` helped out! I think the description in the documentation is the best we have right now...

**Comment by wazedxwxx** [comment]
Thank you! My issue is solved, I will close it.
