### ISSUE TITLE
unable to access 'https://github.com/LLNL/sundials/'

### ISSUE THREAD

**Issue by WHEREISSHE** [AMReX-Combustion/PeleC#499]
When I am trying `make`, it goes wrong with a NOTE---"fatal: unable to access 'https://github.com/LLNL/sundials/': SSL: certificate subject name (*.googlevideo.com) does not match target host name 'github.com'
make: *** [GNUmakefile:228: /soft/PELEC/Submodules/PelePhysics/ThirdParty/BUILD/SUNDIALS/src/include/sundials/sundials_config.in] Error 128." And both in PeleC and PeleM, I get troubles to make sundials component work well. Should I `cmake` it first or just run` make TPL`?

**Comment by czc-zju** [comment]
You have not installed sundials and you can try the following steps:
1> git clone https://github.com/LLNL/sundials
2> cd sundials
3> mkdir build
4> cd build
5> cmake ..
6> sudo make install

**Comment by WHEREISSHE** [comment]
> You have not installed sundials and you can try the following steps: 1> git clone https://github.com/LLNL/sundials 2> cd sundials 3> mkdir build 4> cd build 5> cmake .. 6> sudo make install

Thanks. I followed your steps. It seems worked but it's not completely fixed. Now the error saying---tmp_build_dir/o/3d.gnu.EXE/ReactorCvodePreconditioner.o: in function `pele::physics::reactions::cvode::PSolve(double, _generic_N_Vector*, _generic_N_Vector*, _generic_N_Vector*, _generic_N_Vector*, double, double, int, void*)':
/soft/PELEC/Exec/RegTests/PMF/../../../Submodules/PelePhysics/Reactions/ReactorCvodePreconditioner.cpp:310: undefined reference to `SUNDlsMat_denseGETRS'
collect2: error: ld returned 1 exit status
make: *** [../../../Submodules/AMReX/Tools/GNUMake/Make.rules:56: PeleC3d.gnu.ex] Error 1, which have been showed when I run `RegTests` in PeleM. If you know why this happened, please tell me. Thanks again for your kind help.

**Comment by jrood-nrel** [comment]
Does `make TPL` work?

**Comment by WHEREISSHE** [comment]
> Does `make TPL` work?

Yeah! But even I have followed the sundials installation steps recommened by @czc-cfd , the error ---fatal: unable to access 'https://github.com/LLNL/sundials/': Failed to connect to github.com port 443 after 21261 ms: Connection refused
make[1]: *** [GNUmakefile:228: /soft/PELEC/Submodules/PelePhysics/ThirdParty/BUILD/SUNDIALS/src/include/sundials/sundials_config.in] Error 128
make[1]: Leaving directory '/soft/PELEC/Submodules/PelePhysics/ThirdParty'
make: *** [../../../Exec/Make.PeleC:148: TPL] Error 2---occured when I `make TPL`

**Comment by esclapez** [comment]
It looks like you are unable to access the open LLNL github repository. If you're trying to compile on the compute node of a cluster or your local machine is protected by firewalls, this might happen. Can you make sure access to github repositories is available in your environment ?

**Comment by WHEREISSHE** [comment]
> It looks like you are unable to access the open LLNL github repository. If you're trying to compile on the compute node of a cluster or your local machine is protected by firewalls, this might happen. Can you make sure access to github repositories is available in your env

> It looks like you are unable to access the open LLNL github repository. If you're trying to compile on the compute node of a cluster or your local machine is protected by firewalls, this might happen. Can you make sure access to github repositories is available in your environment ?

Thanks, I checked my network. It seemed that my clash didn't work properly in virtual machine. Is there any alternative options?

**Comment by jrood-nrel** [comment]
You will need to be able to `git clone https://github.com/LLNL/sundials.git` somewhere for installing SUNDIALS to work. How were you able to clone Pele?

**Comment by WHEREISSHE** [comment]
> You will need to be able to `git clone https://github.com/LLNL/sundials.git` somewhere for installing SUNDIALS to work. How were you able to clone Pele?

I cloned it in Windows platform. Besides, I also downloaded files directly from Github. I think it should be the same.

**Comment by WHEREISSHE** [comment]
I fixed my network problem and confirmed it by `ping github.com`. But it sitll went wrong with message---fatal: unable to access 'https://github.com/LLNL/sundials/': SSL: certificate subject name (*.googlevideo.com) does not match target host name 'github.com'
make[1]: *** [GNUmakefile:228: /soft/PELEC/Submodules/PelePhysics/ThirdParty/BUILD/SUNDIALS/src/include/sundials/sundials_config.in] Error 128.
