### ISSUE TITLE
NoSlipWall in pelelm and pelec

### ISSUE THREAD

**Issue by czc-zju** [AMReX-Combustion/PeleC#502]
The following two cases are calculated by PeleLM and PeleC. In the results of PeleLM, we can see clear boundary layers, the velocity is very small, but the result of PeleC has no boundary layer, and the velocity on the vertical line is equal, why?
![图片1](https://user-images.githubusercontent.com/81547457/169676330-4a3d2c77-66bf-4455-9945-e3f508e7dbf7.png)

**Comment by marchdf** [comment]
Please post your PeleC input file. Thanks!

**Comment by czc-zju** [comment]
[example_inp.txt](https://github.com/AMReX-Combustion/PeleC/files/8750622/example_inp.txt)

**Comment by czc-zju** [comment]
> 请张贴您的 PeleC 输入文件。谢谢！

I have tried many cases, but this problem can't be solved. 
Do I need to provide any other files?

**Comment by marchdf** [comment]
Thanks for providing the input file. The first thing I see is that you have `pelec.diffuse_vel = 0`, which means that velocity diffusion is turned off, which means you have slip walls and not "no slip" walls, which would give a result as you see in PeleC. Switch it to `pelec.diffuse_vel = 1`. If this is multi-species, you should also turn on species diffusion.

**Comment by drummerdoc** [comment]
Oops, switch to  pelec.diffuse_vel = 1 :)

**Comment by czc-zju** [comment]
Thanks a million.

**Comment by czc-zju** [comment]
I set NoSlipWall in my case in peleC, and I also set it as an isothermal wall (the following is my setting process), but the isothermal wall is not displayed in the figure. Is there something wrong with my method?
![2022-05-25_225810](https://user-images.githubusercontent.com/81547457/170296240-e302c9ed-696f-4a4d-84ea-ccf39fe336cf.png)

   _if (idir == 1 )  {
    auto eos = pele::physics::PhysicsType::eos();
    amrex::Real massfrac[NUM_SPECIES] = {0.0};
    for (int n = 0; n < NUM_SPECIES; n++)
    massfrac[n] = s_int[UFS + n] / s_int[URHO];
    const amrex::Real T = 500;
    amrex::Real eint=0.0;
    eos.RTY2E(s_int[URHO], T, massfrac, eint);
    s_ext[URHO] = s_int[URHO];
    s_ext[UMX] = 0.0;
    s_ext[UMY] = 0.0;
    s_ext[UMZ] = 0.0;
    s_ext[UEINT] = eint*s_ext[URHO];
    s_ext[UEDEN] = eint*s_ext[URHO];
    s_ext[UTEMP] = 500;
    for (int n = 0; n < NUM_SPECIES; n++) {
      s_ext[UFS + n] = s_int[UFS + n];
    }
}_

**Comment by marchdf** [comment]
What flow quantity are you plotting here? What does your input file look like? Do you have this in the input file?
```
pelec.eb_boundary_T = 500.
pelec.eb_isothermal = 1
```

**Comment by czc-zju** [comment]
Temperature.
[example.txt](https://github.com/AMReX-Combustion/PeleC/files/8776129/example.txt)

I want to set isothermal boundaries for the tube wall and EB, but it doesn't work very well

**Comment by marchdf** [comment]
@baperry2 you've done heat conduction with EB in the past to verify the capability. Do you see anything wrong with this input file?

**Comment by czc-zju** [comment]
I want to have a gradient in the temperature at the wall, such as in the following figure, which shows the temperature field, but it is calculated by PeleLM (isothermal boundaries for the wall). 
![2022-05-26_231849](https://user-images.githubusercontent.com/81547457/170520439-006fc934-83fb-4e98-98a4-4f333541d67a.png)

**Comment by hsitaram** [comment]
It looks like you want gradients at the cartesian face at the bottom. If you set it as no-slip wall, your if(idir==1) conditions from bcnormal will be ignored. By default the "noslipwall" is adiabatic. if you want to set it as an isothermal wall, use "Hard" there.

pelec.lo_bc       =   "Hard"  "Hard" 
pelec.hi_bc       =   "FOExtrap" "NoSlipWall"

**Comment by baperry2** [comment]
@czc-zju the inputs file you posted should be sufficient for setting the isothermal condition at the EB surface. Let me know if you ware still having trouble at the EB surface after implementing these changes. You can also see regtests EB-C4-5 for examples with an isothermal EB boundary. 

The changes @hsitaram recommends should fix the boundary condition at the lower boundary.

**Comment by czc-zju** [comment]
@[baperry2](https://github.com/baperry2) @[hsitaram](https://github.com/hsitaram)@[marchdf](https://github.com/marchdf)
  This scheme that uses "Hard" there works great, as follows
![2022-05-27_093427](https://user-images.githubusercontent.com/81547457/170611191-60295806-8221-4792-864c-45e00bf0f268.png)

My settings are as follows:
input file:
pelec.lo_bc       =   "Hard"  "Hard" 
pelec.hi_bc       =   "FOExtrap" "NoSlipWall" 

prob.H:
  if (idir == 1 )  {
  s_ext[UMX] = 0.0;
  s_ext[UMY] = 0.0;
  s_ext[UMZ] = 0.0;
 s_ext[UTEMP] = 500;
}

**Comment by hsitaram** [comment]
great! It would be better to do an odd reflection, ie s_ext[UMX]=-s_int[UMX] etc.. for momentum and similarly for temperature as s_ext[UTEMP]=2*500-s_int[UTEMP]

**Comment by czc-zju** [comment]
Do you mean set like this：

  s_ext[URHO] = s_int[URHO];
  s_ext[UMX] = -s_int[UMX];
  s_ext[UMY] = -s_int[UMY];
  s_ext[UMZ] = -s_int[UMZ];
  s_ext[UEINT] = s_int[UEINT];
  s_ext[UEDEN] = s_int[UEDEN];
  s_ext[UTEMP] = 2*500-s_int[UTEMP];
  for (int n = 0; n < NUM_SPECIES; n++)
    s_ext[UFS + n] = s_int[UFS + n];

**Comment by hsitaram** [comment]
yes, looks good!

**Comment by czc-zju** [comment]
Fantastic!!!
I have tried it and it works perfectly!!!
thanks a lot.

**Comment by hsitaram** [comment]
looks like you set pelec.diffuse_vel=0, it should be 1 if you want viscous
effects

**Comment by RSuryaNarayan** [comment]
@hsitaram just clarifying things here

Aren't UTEMP and UEINT supposedly "derived" variables as per the docs? So shouldn't we be setting the Isothermal BC in a conservative sense based on UEDEN rather than UTEMP?

I tried a very simple case involving a rectangular channel with the top and bottom walls at 2500K and air inside the channel at zero velocity with an initial temperature of 300K like so: 

![image](https://user-images.githubusercontent.com/52670594/195750686-ae1e2806-49b1-4b0d-a24e-25975fd3e99d.png)

Zero gradient for UEDEN and UEINT and the dirchlet for UTEMP didn't seem to cause any rise in temperature of the air inside. However, setting the same BC in a conservative sense on UEDEN like the following does seem to work:
```
 if(idir == 1)
{ 
  amrex::Real grad, T_x, massfrac[NUM_SPECIES], e_wall;
  
  grad = (prob_parm.T_s1-prob_parm.T_s0)/L_x;
  T_x = prob_parm.T_s1 - grad *  x[0];

  auto eos = pele::physics::PhysicsType::eos();

  for (int n=0;n<NUM_SPECIES; ++n){
   massfrac[n] = s_int[UFS+n]/s_int[URHO];
   s_ext[UFS+n] = s_int[UFS+n];
   }

  eos.TY2E(T_x, massfrac, e_wall);

  //Assign everything else properly
  s_ext[URHO] = s_int[URHO];
  s_ext[UMX] = -1*s_int[UMX];
  s_ext[UMY] = -1*s_int[UMY];
  s_ext[UMZ] = -1*s_int[UMZ];
  for (int n = 0; n < NUM_SPECIES; n++){
     s_ext[UFS + n] = s_int[UFS + n];}
     
  s_ext[UEDEN] = 2*s_int[URHO]*e_wall-s_int[UEDEN];
  
//dropped UTEMP and UEINT as they are anyway redundant variables
}
```

**Comment by hsitaram** [comment]
Hi Surya,

Thank you for bringing this up.

UTEMP is actually not in the list of derived variables. Setting UEDEN like
the way you did can change the hyperbolic flux at the wall, which is why I
suggested the UTEMP fix.
if you change UEDEN, you change the pressure at the wall, resulting in a
non-zero pressure gradient (dpdn), which is not correct.
Therefore, changing only UTEMP would impose just a thermal diffusive flux
and no changes to hyperbolics.

That said, as of now, changing UTEMP in bcnormal is not changing anything,
as the wall is behaving like it is adiabatic.
Although, commenting out this line -
https://github.com/AMReX-Combustion/PeleC/blob/ff51a0c37af5fc74e0baad3ae06991f93a7e6704/Source/Utilities.H#L231
should fix the thermal diffusion flux without any issues. Let me discuss
with my colleagues here before deeming this change safe. I can see the
correct behavior, see below:
![Screen Shot 2022-10-13 at 10 47 11 PM](https://user-images.githubusercontent.com/7399475/195764859-670704d8-d7b7-4f72-8af1-c3420a20c227.png)

**Comment by RSuryaNarayan** [comment]
@hsitaram Thanks for the prompt follow-up with this! I remember discussing the same thing in the past in #263 and it seemed to work there. I assumed the code must have changed in-between and we need to specify based on energy! Thanks once again!

**Comment by RSuryaNarayan** [comment]
@hsitaram will this change work?

**Comment by hsitaram** [comment]
Hi Surya,

I had a discussion with my colleague Marc H and the hack (removing the
REY2T call) I mentioned earlier should be ok.
I checked if there were any changes to regression tests with this change.
They were negligible, at least for the PMF case.
I strongly suggest not implementing the isothermal wall bc through UEDEN as
you will affect the hyperbolic flux.

We also discussed if we need to add a new BC for isothermal wall along with
slip/noSlip BCs,
which would require some effort on our side to perform checks while
assigning ghost cell quantities. will keep you posted on this.

It will be good to hear from you again if it works out for you.

Thanks,
Hari

**Comment by RSuryaNarayan** [comment]
Hello Hari, 
Thanks for the detailed follow-up with this. Really appreciated it! 
I will implement the isothermal wall with UTEMP as you suggested and let you know what results I get. 

The case I am running is similar to what I showed in the graphic in my previous comment except that the wall is now NoSlip for which I plan to simply reflect the velocities. 

Thanks once again!

**Comment by RSuryaNarayan** [comment]
Hello Hari
I have a question with the ```2*T_wall-s_int[UTEMP]``` approch. Locally it is possible that ```s_int[UTEMP]``` crosses ```2*T_wall```, in which case the ghost cell temperature goes negative. So would it just be okay to impose ```T_wall``` instead?

**Comment by drummerdoc** [comment]
Is this only for evaluating the gradient?  That is, will the T that comes from that formula be used to evaluate any EOS or transport coefficient calls?

**Comment by RSuryaNarayan** [comment]
@drummerdoc we use that to set ```s_ext[UTEMP]``` to impose an isothermal wall

**Comment by hsitaram** [comment]
that ghost T does go into EOS calls. So we need to be careful here.
s_int[UTEMP] may be the safest option.

**Comment by RSuryaNarayan** [comment]
Wouldn't that set it back to adiabatic wall? For now something that seems to work is just T_wall

**Comment by hsitaram** [comment]
my bad. use s_ext[UTEMP] to be T_wall.

**Comment by RSuryaNarayan** [comment]
Thanks!
