### ISSUE TITLE
amrex::Abort::0::Unable to open input file Turb.test2/HDR !!!

### ISSUE THREAD

**Issue by WHEREISSHE** [AMReX-Combustion/PeleC#513]
HI, there's something wrong when I tried to run `Exec/Production/ChallengeProblem` with error note:
```
Initializing turbInflow inj1 with file Turb.test2 (location coordinates in will be scaled by 1 and velocity out to be scaled by 100) 
amrex::Abort::0::Unable to open input file Turb.test2/HDR !!!
SIGABRT
See Backtrace.0 file for details
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```
I had no idea what exactly caused it. Could you please offer me some advice? 
THANKS!

**Comment by drummerdoc** [comment]
This case is set up to add turbulent fluctuations to a mean inflow profile for the four jets coming into the top of the domain for a closed piston bowl. The fluctuations are read from a precomputed file of homogeneous isotropic turbulence. For this case, the file we use is too large to commit into git. 

If you comment out the turb file name (Turb.test2) in the inputs it should shut off that but and flow in only mean profiles.

**Comment by WHEREISSHE** [comment]
> This case is set up to add turbulent fluctuations to a mean inflow profile for the four jets coming into the top of the domain for a closed piston bowl. The fluctuations are read from a precomputed file of homogeneous isotropic turbulence. For this case, the file we use is too large to commit into git.
> 
> If you comment out the turb file name (Turb.test2) in the inputs it should shut off that but and flow in only mean profiles.

OK！got it. THank you!

**Comment by SRkumar97** [comment]
> This case is set up to add turbulent fluctuations to a mean inflow profile for the four jets coming into the top of the domain for a closed piston bowl. The fluctuations are read from a precomputed file of homogeneous isotropic turbulence. For this case, the file we use is too large to commit into git.
> 
> If you comment out the turb file name (Turb.test2) in the inputs it should shut off that but and flow in only mean profiles.

Hi, I'm interested to run and visualize this testcase. Could you kindly share the Turb.test2 file by some other means, such as a drive link?
Thanks

**Comment by baperry2** [comment]
You can generate turbulence files of the appropriate format for the PeleC turb inflow capability using the TurbFileHIT support code from PelePhysics: https://amrex-combustion.github.io/PelePhysics/Support.html#sec-turbfile

**Comment by SRkumar97** [comment]
> You can generate turbulence files of the appropriate format for the PeleC turb inflow capability using the TurbFileHIT support code from PelePhysics: https://amrex-combustion.github.io/PelePhysics/Support.html#sec-turbfile

Thank you, I'll look into this.
