### ISSUE TITLE
Trouble restarting from plt file

### ISSUE THREAD

**Issue by whitmanscu** [AMReX-Combustion/PeleC#516]
Hello, I'm trying to restart from a plt file as recent chk files were damaged by system corruption. However, for this particular case I'm getting errors such as: `amrex::Abort::32::Species mass fraction don't sum to 1. The sum is: 0.000000 !!!` I've seen related issues before for different cases where the sum was off from 1 that I was able to correct through the massfrac initialization tolerance setting, but in this case it reading zero suggests something else is the matter.

I believe this plt file is intact and definitely should have species data as well. For example, I'm able to load it in yt and view species data including calculating average species concentrations. Do you have any suggestions as to how I should go about figuring out what's wrong with this plt file or restart method? Unfortunately the case is quite large so I can't share an easily reproducible example.

**Comment by marchdf** [comment]
Hi! That sounds very annoying... This error is making me think that somehow it is not entering [this loop](https://github.com/AMReX-Combustion/PeleC/blob/development/Source/IO.cpp#L792). Is there maybe a different mechanism being used for this case than the one that was used for this data? Can you check to see if it is entering that loop?

**Comment by whitmanscu** [comment]
Oh you know what it is? Looking at that code made me realize that I haven't been plotting the mass fractions, just the concentrations for each species. For whatever reason that's what my version of PeleC from last year did by default.

It looks like that restart code is set up to only handle mass fractions, however. I would think it would be pretty straightforward to have it handle concentrations instead of mass fractions, maybe using a parm_parse setting to toggle. I can try and get this working for this particular case as I'm not sure it makes sense to implement moving forward, if the Y(spec) fields will be plotted automatically in the future, as seems to be the case. I can let you know if I run into any troubles.

**Comment by marchdf** [comment]
Oh interesting. There should at least be a check on that and give the user a sane error message. And yes absolutely, it would be cool to expand to concentrations as well. Please let us know if you have any other questions.

**Comment by whitmanscu** [comment]
Restarting from concentrations worked well - I just added a bool switch and set it to check rho_spec instead of Y(spec), then divided by the density.

I do have an additional related but separate issue that I'll post here for now since I'm not sure it warrants its own topic. Specifically I lost the chk files for a much older case that was using the NSCBC boundaries from before the C++ migration. I was able to switch to simpler BC types and restart from a plt file. I would now like to use the newly generated chk file to restart the pre-migration executable, however when I try to do so I get the message `unexpected token in RealBox: ` in the error file.

I'm guessing that this sort of backwards compatibility is likely a lost cause, but if you have any ideas on how to enable a restart I'd be curious. Alternatively, I see there are two branches with some nscbc capabilities that were last updated in 2021. Are either of those recommended for trying an NSCBC case with a more modern version of the code? Thanks!

**Comment by drummerdoc** [comment]
Yeah, NSCBC is a work-in-progress.  There are several examples in Exec of subsonic outflow following the formulation specified in the Blazek textbook, where pressure is extrapolated on the out and set on the in side, but nobody is currently incorporating the Fortran-based inert-gas NSCBC conditions that were in much earlier versions of PeleC.  You might try copying the examples and see how they work...should be ok as long as reactions stay away from the outlet.  Ping @marchdf or @baperry2 for more info, if needed.

As far as restarts...yeah, there's gonna be backward compatibility issues there are are tough to get around elegantly.  One hacked approach is to simply Unix-diff the (ASCII) Header files within the current and old versions - it's likely that the difference is trivial and you can just hand-edit it to be compatible. Let me know if that doesn't turn up something manageable.

**Comment by whitmanscu** [comment]
Hm, interesting. I've been using the Blazek subsonic outflow for most of my cases and it works decently well, even with reactions, but I do sometimes get a bit of vortex meandering with strong vortex cores hitting the outflow that I'm hoping to avoid. I'll try diffing the Headers and see what that turns up - thanks!

**Comment by baperry2** [comment]
"it works decently well" is a pretty good summary of my experience with that outflow BC. It's worked well enough even for reacting cases that implementing NSCBC hasn't become a priority, but we do see weird/unintended behavior sometimes.

**Comment by whitmanscu** [comment]
I'm going to go ahead and close this issue as I was able to restart from concentrations successfully, and the NSCBC question is outside the original scope (and no longer relevant for me). Thanks for the assistance on this one!

**Comment by zyx1xyz** [comment]
Hello, I restart directly from the plt file without changing any parameters and get errors:
`amrex::Abort::31::Species mass fraction don't sum to 1. The sum is: 0.999999!`
By the way, does this restart method support expanding the computation region?

**Comment by baperry2** [comment]
It appears there is an issue with the data in your plt file with the mass fractions not summing to unity and you'd have to open that and check where the issue is. You could also check the `sumYminus1` min/max that get printed when you run your simulation, which should be order of machine zero.

In your case the discrepancy from 1 appears to small, so you may also be able to safely increase the tolerance for this by specifying a value for `pelec.init_pltfile_massfrac_tol` in your simulation.

**Comment by baperry2** [comment]
Also, this restart method does not support modifying the computational domain.
