### ISSUE TITLE
unsuccessful make -- undefined references to multiple variables

### ISSUE THREAD

**Issue by lihaiyue** [AMReX-Combustion/PeleC#530]
![bug](https://user-images.githubusercontent.com/23021167/179522371-e9680d95-7cb5-4cb4-b32b-bc3b20819a75.png)

The installation is unsuccessful when I use make

undefined references to multiple variables are observed.

**Comment by jrood-nrel** [comment]
Can you try `make TPL` before `make`?

**Comment by lihaiyue** [comment]
Yes, make TPL is successful

**Comment by lihaiyue** [comment]
And now I have successfully complied a previous version (Bugfixed_molefraction_drive, v 0.2)

**Comment by jrood-nrel** [comment]
Ok great.
