### ISSUE TITLE
How to generate a 2D PMF case?

### ISSUE THREAD

**Issue by lihaiyue** [AMReX-Combustion/PeleC#531]
I’d like to generate a 2D PMF case.

If I simply change the dimension in GNUmake into 2, the information in z axis is reduced.

however, the information in Z axis is the most important using the default settings. 

What should I do to reduce the information in x or y?

**Comment by wazedxwxx** [comment]
Hi,haiyue. 
I suggest swap the order of the z direction in the pc_initdata() function in Prob.cpp.

**Comment by marchdf** [comment]
yes, AMReX assumes that the third dimension is z so you would have to flip the problem so that the dimension of interest is x or y when you go to 2D.
