### ISSUE TITLE
#52 Broke compiling with `HYP_TYPE=MOL USE_EB=TRUE`

### ISSUE THREAD

**Issue by marchdf** [AMReX-Combustion/PeleC#56]
Regression test MMS6 and MMS7 use the following in the compile line: `HYP_TYPE=MOL USE_EB=TRUE`. These tests failed to compile last night. As far as I can tell this is because #52 introduces the following in line 122 of `PeleC/Exec/Make.PeleC`:
```
Pdirs := Base EB Amr Boundary AmrCore F_Interfaces F_Interfaces/Base
```

If I remove `F_Interfaces F_Interfaces/Base` from that line, then I can compile the test cases again. I don't want to do that because they might be there for a good reason for this so I am looking for guidance on how to fix. Tagging @marient @drummerdoc @rgrout and @jrood-nrel because you might have toughts. Thanks!

**Comment by rgrout** [comment]
F_Interfaces shouldn't be included - there's no Make.Package there, it should just be F_Interfaces/Base. In any case both are redundant with the F_Interfaces/Base include lines lower down in the makefile... cleaned it up and testing now, thx.

**Comment by marchdf** [comment]
Thanks @rgrout !

**Comment by rgrout** [comment]
Think it's fixed... closing.
