### ISSUE TITLE
A question about function "pc_fill_bndry_grad_stencil_quadratic()" in EB.cpp

### ISSUE THREAD

**Issue by wazedxwxx** [AMReX-Combustion/PeleC#564]
Hey Everyone
In pc_fill_bndry_grad_stencil_quadratic() function
```
      amrex::Real y[2] = {
        b[1] + (x[0] - b[0]) * amrex::Math::abs(n[c[1]] / n[c[0]]),
        b[1] + (x[1] - b[0]) * amrex::Math::abs(n[c[1]] / n[c[0]])};
```
Why is this `n[c[1]] / n[c[0]`?  Refer Johansen's paper, this point is perpendicular to the EB boundary. I think this code works out along the EB boundary. I don't know if I understand something wrong.  I would appreciate it if you could answer.

**Comment by hsitaram** [comment]
Hi @wazedxwxx - Thank you for reaching out.

This function uses the quadratic stencil for finding gradient of a field at the EB, when the EB holds a dirichlet condition. You need 2 additional points along the EB normal for quadratic interpolation. This is first obtained through the lines you shared. The function first finds the dominant component of the normal (c[0]), moves a distance dx and 2*dx along the dominant normal direction and locates the corresponding transverse coordinates. Then a bilinear interpolation is performed over the 3 x 3 stencil to get the field values at these points. After this a quadratic reconstruction is done and gradients obtained.

We were hoping to have some documentation added to readthedocs. But attached is an excerpt from some of my notes.

[EB_stencils.pdf](https://github.com/AMReX-Combustion/PeleC/files/9957709/EB_stencils.pdf)

**Comment by wazedxwxx** [comment]
Thank you. This helped me a lot. @hsitaram
