### ISSUE TITLE
The stress in embedded boundary

### ISSUE THREAD

**Issue by wazedxwxx** [AMReX-Combustion/PeleC#565]
Hi, everyone.  I find $\tau$ in function "pc_apply_eb_boundry_visc_flux_stencil"  set as follows
```
      const amrex::Real tauDotN[AMREX_SPACEDIM] = {AMREX_D_DECL(
        (static_cast<amrex::Real>(4.0 / 3.0) * coeff(iv, dComp_mu) +
         coeff(iv, dComp_xi)) *
          dUtdn[0],
        coeff(iv, dComp_mu) * dUtdn[1], coeff(iv, dComp_mu) * dUtdn[2])};
```
I understand that this code caculate $\(\tau_{nn},\tau_{nt}\)$ in 2D, where  `coeff(iv, dComp_mu)`  is viscosity $\mu$, `coeff(iv, dComp_xi)` is bulk viscosity $\xi$ , `dUtdn[0]` is normal velocity gradient $\frac{\partial U_n }{\partial n}$ . 
I don't understand something about this code.  The stress $\tau_{nn}$ can be written as $\tau_{nn} = 2\mu \frac{\partial U_n }{\partial n}  + \xi div U$. Apply Stokes' hypothesis $\xi = - \frac{2}{3}\mu$, the equation can be written as  $\tau_{nn} = \frac{4}{3}\mu \frac{\partial U_n }{\partial n}  + \xi \frac{\partial U_t }{\partial t}$. Actually the code calculates $\tau_{nn} = \frac{4}{3}\mu \frac{\partial U_n }{\partial n}  + \xi \frac{\partial U_n}{\partial n}$.

I can't fully understand this code, if you can help me I would be very grateful!

**Comment by hsitaram** [comment]
Hi @wazedxwxx  

I should have sent you the whole document earlier. Apologies. See attached formulation for viscous flux. There are two things to note

1) dut/dt is 0 as the EB is treated as a no-slip wall BC everywhere
2) the second term in the stress is actually (k-2/3 mu)* (del U). The Stokes hypothesis is already accounted for.

[viscous_flux_EB.pdf](https://github.com/AMReX-Combustion/PeleC/files/9977361/viscous_flux_EB.pdf)

**Comment by wazedxwxx** [comment]
Thank you very much. @hsitaram This is exactly what I need!
