### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by JayStandridge** [AMReX-Combustion/PeleC#566]
Hi all,

I just cloned the PeleC repo using git clone --recursive, and when I try to compile the code I receive the following error: 
![image](https://user-images.githubusercontent.com/27370774/202016294-a18ca0f1-1918-4369-bff3-3801e2ba82cc.png)

I have been using PeleC for a while, and noticed the issue after I pulled down the latest version.
I pulled down the latest version so I could check out ntw/add_plot_derivs and noticed that before I ran git checkout that I was unable to compile. I then made a new clone and still got the issue. What is going on?

TIA

**Comment by jrood-nrel** [comment]
It looks like sundials has not been built. Do you use `make TPL` to build it? https://github.com/AMReX-Combustion/PeleC/blob/development/README.rst#getting-started . If so, you will want to look at why sundials failed.
