### ISSUE TITLE
Cvode Failed in a simple two-dimensional case

### ISSUE THREAD

**Issue by yeanment** [AMReX-Combustion/PeleC#594]
I am using PeleC for the computation of a detonation wave, and expected to obtain cellular structures of a propagating detonation wave. A schematic of the computation domain is shown below. A small regime of unburnt gas with a high temperature and pressure is  placed at the left for initialization of the detonation wave. The right is filled with unburnt gas. For illustration, the stoichiometric hydrogen/air are considered.
![image](https://user-images.githubusercontent.com/38305958/213140759-8d184ac4-f39a-4c3f-bd5f-1e16e73181a7.png)

However, the computation failed quite rapidly with a cvode error message. I check the output, and find nothing nonphysical. I also tried to change the CFL number, max refine level and ode parameters. But, I failed to find a solution. Could you give some assistance on this issue? I also attached the code for initialization and computation. Please check the DetoCell_XH2_2D.zip for more details.

It's also noted that sometimes I cannot use a high level of refine ratios. The program fails repeatedly. But when I change to a small refine ratios, typically 1 or 2, the program works just fine. What's the possible reason for this phenomenon? Is it related to the sub-cycling step procedure, or just inappropriate choice of refinement criteria?

Thanks in advance.
 
[DetoCell_XH2_2D.zip](https://github.com/AMReX-Combustion/PeleC/files/10444495/DetoCell_XH2_2D.zip)

**Comment by marchdf** [comment]
Hi, I just noticed this issue when going through the backlog. Has this been addressed?

**Comment by yeanment** [comment]
Yes, I have found a way to solve this issue.

**Comment by zyx1xyz** [comment]
Hi, I also encountered a similar problem, can you share how you solved it?

**Comment by yeanment** [comment]
> Hi, I also encountered a similar problem, can you share how you solved it?

I haven't used this code for a long time. As far as I can remember, I change the time-stepping method and then it works.
