### ISSUE TITLE
Ensure unnecessary operations are not carried out in covered regions

### ISSUE THREAD

**Issue by baperry2** [AMReX-Combustion/PeleC#703]
PR https://github.com/AMReX-Combustion/PeleC/pull/702 ensures consistency in setting the state in covered cells. Presently, valid data state is required in covered cells because some operations, such as `bcnormal` to populate ghost cells at domain boundaries, are called for covered cells, even though that's not strictly necessary and shouldn't affect the solution. We should remove these unneeded operations (perhaps by temporarily setting the covered state to something invalid, like all zeros, to chase down any such instances).

**Comment by marchdf** [comment]
I just tried this and it breaks immediately here: https://github.com/AMReX-Combustion/PeleC/blob/development/Source/Derive.cpp#L134. This feels very annoying because we don't have access to the factory/cell flags in any of the derived functions. We don't have access to the call site of those functions so we can't pass it in. I don't think (?) that we can access that information from anything that we have access to:

```
pc_derkineng(
  const amrex::Box& bx,
  amrex::FArrayBox& derfab,
  int /*dcomp*/,
  int /*ncomp*/,
  const amrex::FArrayBox& datfab,
  const amrex::Geometry& /*geomdata*/,
  amrex::Real /*time*/,
  const int* /*bcrec*/,
  const int /*level*/)
```

**Comment by baperry2** [comment]
Yeah as far as I can tell modifying this would require the interface to be changed within `AmrLevel`. So at least for the derives we can't eliminate these operations. We could still put invalid values in the covered cells and run as a debugging exercise to see whether any nans propagate into the valid cells, but would have to check for this manually rather than with AMReX FPE trapping.

**Comment by marchdf** [comment]
I was being dumb. We do this for enstrophy: https://github.com/AMReX-Combustion/PeleC/blob/bb3a609e452e7f3cb0976964ecb8eb25f31e2dcd/Source/Derive.cpp#L388. So we could technically mask out the derives based on the cell EB flag. What do we think?

**Comment by marchdf** [comment]
well maybe we keep this going one day. I have a couple branches locally that tries to track this down. It gets... messy.

**Comment by baperry2** [comment]
I tried running EB-C3 and setting the body state to 1.0 for all variables. I get NaNs that start only in the covered region but march inward with each timestep. That indicates we might be touching the covered cells unintentionally somewhere during the fluid cell updates. Might not be worth hunting down and eliminating all the covered cell computations, but I'll take a look and see if I can find where this would be happening.
