### ISSUE TITLE
How to impose an outflow condition at the EB?

### ISSUE THREAD

**Issue by Toby-Yang** [AMReX-Combustion/PeleC#737]
I need to simulate flame propagation in a complex geometry with open boundary. Is it possible to use outflow or FOEXTRAP boundary condition at the EB in PeleC?

**Comment by baperry2** [comment]
Presently, PeleC only supports EBs as walls (slip or noslip, adiabatic or isothermal) and you cannot set an inflow or outflow on the EB. 

A while back, there was some effort to implement inflows on EBs (https://github.com/AMReX-Combustion/PeleC/pull/391, https://github.com/AMReX-Combustion/PeleC/issues/251). We were never quite satisfied with that implementation, but it might be possible to hack something similar for outflows on EBs.

**Comment by Toby-Yang** [comment]
I see. Thanks for your suggestions.
