### ISSUE TITLE
Diagnostic output parm-parse variables "unused" after restart

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleC#747]
For debugging purposes, I was trying to restart a case from a checkpoint and change the diagnostic slice file output frequency (by changing ```pelec.xnormP.int```) but it wasn't updating its frequency. 

It works fine when I run the case from the beginning.

So after restart, I checked if those diagnostic inputs were even being read-in by running for a single timestep. I get the following message:

```
Ending run at 16:44:33 UTC on 2024-01-26.
Run time = 9.351523563
Run time w/o init = 9.333585459
Unused ParmParse Variables:
  [TOP]::pelec.diagnostics(nvals = 1)  :: [xNormPlane]
  [TOP]::pelec.xNormPlane.type(nvals = 1)  :: [DiagFramePlane]
  [TOP]::pelec.xNormPlane.file(nvals = 1)  :: [xNormCent]
  [TOP]::pelec.xNormPlane.normal(nvals = 1)  :: [0]
  [TOP]::pelec.xNormPlane.center(nvals = 1)  :: [0.15625]
  [TOP]::pelec.xNormPlane.int(nvals = 1)  :: [5]
  [TOP]::pelec.xNormPlane.field_names(nvals = 10)  :: [density, zmom, xmom, Temp, heatRelease, z_velocity, x_velocity, Y(H2), Y(HO2), pressure]
  [TOP]::pelec.xNormPlane.int(nvals = 1)  :: [1]

```

Tested this even with ```PMF``` case...

**Comment by baperry2** [comment]
Good catch, this is a bug. Diagnostics are not presently initialized when restarting from a checkpoint. PR with the fix incoming.

**Comment by RSuryaNarayan** [comment]
thanks @baperry2 !
