### ISSUE TITLE
How to set up for the axisymmetric configuration?

### ISSUE THREAD

**Issue by EarlFan** [AMReX-Combustion/PeleC#749]
Dear all,

Hi!

I am trying to simulate an axisymmetric problem. Could you please show me the correct geometric setups for the axisymmetric geometry ? 

Results in the .inp formats are appreciated ! ( Noted: the following is just an example and not correct)

`
\# PROBLEM SIZE & GEOMETRY
geometry.is_periodic = 0  0
geometry.coord_sys   = 1  # 0 => cart, 1 => RZ  2=>spherical
geometry.prob_lo     = 0.0  0.0
geometry.prob_hi     = 12 3
amr.n_cell           =  320 80

\# >>>>>>>>>>>>>  BC KEYWORDS <<<<<<<<<<<<<<<<<<<<<<
\# Interior, UserBC, Symmetry, SlipWall, NoSlipWall
\# >>>>>>>>>>>>>  BC KEYWORDS <<<<<<<<<<<<<<<<<<<<<<
pelec.lo_bc       =  "FOExtrap"  "Symmetry"
pelec.hi_bc       =  "FOExtrap"  "FOExtrap"
`

Regards,
Fan E

**Comment by drummerdoc** [comment]
Hey Fan, what you have is close.  The symmetry axis should be the XLO boundary, so 

pelec.lo_bc = Symmetry FOExtrap

should do it.
(note, no quote necessary)

**Comment by baperry2** [comment]
@drummerdoc, I think you're thinking of PeleLMeX

@EarlFan PeleLMeX supports axisymmetric coordinates (example here: https://amrex-combustion.github.io/PeleLMeX/manual/html/Tutorials_HotBubble.html). Unfortunately if the low Mach number approximation is not suitable for your flow of interest, PeleC will abort if you set `geometry.coord_sys = 1` as it isn't set up for that. You'd have to simulate the axisymmetric case as 3D and use an EB to define the axisymmetric boundary, see here for an example: https://amrex-combustion.github.io/PeleC/ebverification/C9/README.html

**Comment by drummerdoc** [comment]
Oops!  thanks Bruce, you are correct.  sorry about that, and thanks for fixing the comment here!

**Comment by EarlFan** [comment]
Dear all, 

@drummerdoc @baperry2 

Thanks for your help!

Regards,
Fan E
