### ISSUE TITLE
Are the Parameters of the Sutherland Model Correct?

### ISSUE THREAD

**Issue by JhonCordova** [AMReX-Combustion/PeleC#800]
Hi everyone,

I've been using the Sutherland model for viscosity calculations in my project, relying on the default parameters provided in the code. I'm seeking confirmation on whether these default parameters are accurate and if there are any common issues or considerations I should be aware of.

```
template <typename EOSType>
struct TransParm<EOSType, SutherlandTransport>
{
  amrex::Real Prandtl_number{0.7};
  amrex::Real viscosity_mu_ref{17.16};
  amrex::Real viscosity_T_ref{273.15};
  amrex::Real viscosity_S{110.4};
  amrex::Real const_bulk_viscosity{0.0};
  amrex::Real const_diffusivity{1.0};
  bool use_soret = false;
};
```

I have compared the default reference viscosity value to what I found in the [literature](https://doc.comsol.com/5.5/doc/com.comsol.help.cfd/cfd_ug_fluidflow_high_mach.08.27.html) and noticed a discrepancy. The literature indicates that the reference viscosity for air should be 17.16 µPa·s, which in the CGS system would be 17.16e-5 P (poise), not just 17.16 as it appears in the code.

To address this, I added the following lines of code to my prob.cpp file:

```
extern "C" {
void
amrex_probinit(
  const int* /*init*/,
  const int* /*name*/,
  const int* /*namelen*/,
  const amrex::Real* /*problo*/,
  const amrex::Real* /*probhi*/)
{
  auto& trans_parm = PeleC::trans_parms.host_trans_parm();
  trans_parm.viscosity_mu_ref = 17.16 / 1e5;
  PeleC::trans_parms.sync_to_device();
}
}
```
Are these modifications adequate for correcting the reference viscosity value in the Sutherland model?
Thank you in advance for your help!

**Comment by baperry2** [comment]
I think you are correct and the default values of the parameters in the Sutherland model in PelePhysics are the wrong order of magnitude. 

Would you be willing to submit a pull request to PelePhysics to correct the default value?

In the meantime, your method of modifying the value in your PeleC case should be correct, but you could also just set `transport.viscosity_mu_ref` in your input file.

**Comment by JhonCordova** [comment]
The pull request has already been made. I also want to inform you that I have included two SGS models (Vreman and WALE) in PeleC locally. These models follow the logic used in the Smagorinsky model. In the next few days, I will submit a pull request to see if you can consider including them in PeleC
