### ISSUE TITLE
Sponge layer_pelec.diffuse_vel 

### ISSUE THREAD

**Issue by vtmaran** [AMReX-Combustion/PeleC#825]
https://github.com/AMReX-Combustion/PeleC/blob/development/Exec/RegTests/EB-ConvergingNozzle/eb-converging-nozzle.inp

pelec.diffuse_vel = 0
prob.do_sponge_zones = 1

pelec.diffuse_vel should be 1 instead of 0 to make the sponge zone work.?

**Comment by baperry2** [comment]
You're right. The sponge zones in this implementation use the standard diffusion, so diffusion has to be on for them to work. That's the case in `example.inp` but not the other input files here. The linked PR fixes the issue. Sorry for the confusion on this!
