### ISSUE TITLE
Dependabot updates not working

### ISSUE THREAD

**Issue by baperry2** [AMReX-Combustion/PeleC#830]
Dependaboit hasn't been submitting submodule update PRs. This has been going on approximately since we updated the submodules to be shallow by default in #821, so perhaps that is interfering with the way dependabot updates them.

**Comment by marchdf** [comment]
well that's annoying...

**Comment by baperry2** [comment]
For posterity,  the full dependabot error was:

```
Dependabot failed to create a pull request
Dependabot ran into an issue when attempting to create the pull request

Dependabot encountered the following error:

POST https://api.github.com/repos/AMReX-Combustion/PeleC/git/refs: 422 - Reference update failed // See: https://docs.github.com/rest/git/refs#create-a-reference
[Troubleshoot Dependabot errors](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```

The issue was not shallow submodules after all. Instead, it was the branch protection rule not allowing new branches to be created. For dependabot to work, it looks like an "always allow" bypass must be created for dependabot.
