### ISSUE TITLE
Help with ignition kernel 

### ISSUE THREAD

**Issue by ghost** [AMReX-Combustion/PeleC#844]
Hello! 

I am doing a research on alcohol spray combustion and using PeleC. I saw a video on Youtube, where the spray is ignited using a  ignition kernel. https://youtu.be/XNKDs0mkym0?t=65 

Please can anyone tell me how to enable this ignition kernel in PeleC? 

Thank you

**Comment by baperry2** [comment]
That is an RCCI engine concept so the ignition kernels form spontaneously due to autoignition. In PeleC, if you want forced ignition, you could code something up for your case using the `problem_modify_ext_sources` user defined function.
