### ISSUE TITLE
Output Control

### ISSUE THREAD

**Issue by zyx1xyz** [AMReX-Combustion/PeleC#858]
How can I control the output of different types of variables at various time steps?

For instance, I need to output pressure data at every time step, while temperature, density, and other variables should be output every 20 time steps.

**Comment by baperry2** [comment]
If you're talking about what variables go in plt files, PeleC does not support this. The variables in each plt file are the same for every plt file dumped by the simulation.

You can use the `Diagnostics` capabilities to create multiple outputs with different frequencies for different variables. This capability supports dumping planes, PDFs, and conditional statistics, but not 3D plots. https://amrex-combustion.github.io/PeleC/InputFiles.html#diagnostic-output
