### ISSUE TITLE
Error::0::Write of Vector<Vector<Real>> failed !!!

### ISSUE THREAD

**Issue by SRkumar97** [AMReX-Combustion/PeleC#889]
Hello!
I am trying to run a multi-noded GPU job, in a computing cluster.
The code began running, at the specified AMR level but broke off somewhere in-between 500-600 iterations with a write vector related error. 

amrex::Error::0::Write of Vector<Vector<Real>> failed !!!
SIGABRT
See Backtrace.0 file for details

The output file frequency was set to every 100 iterations, by which the first 500 iterations' plot and checkpoint files got written properly. Hence I do not understand why the write vector error would appear. Further, the Backtrace.0 file was empty, with no message.
Could someone please help with this error? I am unable to decipher the exact reason for this error.

**Comment by jrood-nrel** [comment]
My guess is that the machine caused the error. Does it fail like this if you keep trying?

**Comment by SRkumar97** [comment]
Thanks, yes found the issue to be rooted to the storage space saturation! Sorry for inconveniences caused. Closing the issue.
